In [7]:
#immporting libraries

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import os
import pandas_bokeh

In [2]:
#prompt for user input of year

# year = input("Please enter year of interest: ")

# # read in the csv for the correct year

# filepath = "Enron_" + year +".csv"
# print(filepath)

# filepath = os.path.abspath('../data/Enron_Kaggle_dataset/Enron_2000.csv') # Subset with 1K Random Emails
filepath = os.path.abspath('../data/Enron_Kaggle_dataset/score.csv') # Full set

df = pd.read_csv(filepath)

In [3]:
# ## Selection for deployment:
# year_of_interest = 1999
# df = df.loc[df['year'] > year_of_interest]
# year_of_interest = 2003
# df = df.loc[df['year'] < year_of_interest]
# df = df.loc[np.random.choice(df.index, 3000, replace=False)] # Random Emails
# display(df.shape)
# df.to_csv('../data/Enron_Kaggle_dataset/Enron_by_year.csv', index=False)

In [4]:
def plot_hr_metrics(dataset):
    #converting the Date column into datetime type
    df=dataset
    df["Date"] = pd.to_datetime(df["Date"])
    scatter = px.scatter(df.groupby(["employee"])["Date"].min().sort_values())

    ### Layout for figure:

    scatter.update_layout(
        title="First mail sent",
        xaxis_title="Employee",
        yaxis_title="Date",
        legend_title="Legend",
        xaxis =  {'showgrid': False},
        yaxis = {'showgrid': True})

    return scatter

In [5]:
df.head()

,email-body,From,employee,Date,Subject,X-Folder,To,X-cc,X-Origin,year,...,anger,anticip,trust,surprise,positive,negative,sadness,disgust,joy,topemotion
0,Here is our forecast,phillip.allen@enron.com,allen-p,2001-05-14 23:39:00+00:00,NaN,'sent mail,tim.belden@enron.com,NaN,Allen-P,2001,...,0.100000,0.100000,0.100000,0.100000,0.100000,0.100000,0.100000,0.100000,0.100000,fear
1,Traveling to have a business meeting takes th...,phillip.allen@enron.com,allen-p,2001-05-04 20:51:00+00:00,Re:,'sent mail,john.lavorato@enron.com,NaN,Allen-P,2001,...,0.094070,0.096115,0.106339,0.089980,0.114519,0.104294,0.100204,0.096115,0.100204,positive
2,test successful. way to go!!!,phillip.allen@enron.com,allen-p,2000-10-18 10:00:00+00:00,Re: test,'sent mail,leah.arsdall@enron.com,NaN,Allen-P,2000,...,0.083333,0.111111,0.111111,0.083333,0.111111,0.111111,0.111111,0.083333,0.111111,anticip
3,"Randy, Can you send me a schedule of the sal...",phillip.allen@enron.com,allen-p,2000-10-23 13:13:00+00:00,NaN,'sent mail,randall.gay@enron.com,NaN,Allen-P,2000,...,0.095238,0.095238,0.142857,0.095238,0.095238,0.095238,0.095238,0.095238,0.095238,trust
4,Let's shoot for Tuesday at 11:45.,phillip.allen@enron.com,allen-p,2000-08-31 12:07:00+00:00,Re: Hello,'sent mail,greg.piper@enron.com,NaN,Allen-P,2000,...,0.250000,0.000000,0.000000,0.000000,0.250000,0.250000,0.000000,0.000000,0.000000,fear